language: node_js
node_js:
  - "8.7.0"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - set -e
  - npm i
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm run test
  - npm run e2e
  - npm run build -- --prod --base-href /

after_success:
  - npm run coverage
  - npm run coveralls
